default: &default
  adapter: postgresql
  encoding: unicode
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRESQL_USERNAME'] || 'postgres' %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] || 'postgres' %>
  host: <%= ENV['POSTGRESQL_HOST'] || 'localhost' %>
  port: <%= ENV['POSTGRESQL_PORT'] || 5432 %>

development:
  <<: *default
  database: kode_weave_development

test:
  <<: *default
  encoding: utf8
  database: kode_weave_test

production:
  <<: *default
  database: kode_weave_production
  username: kode_weave
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>
